controller_type: JOINT_IMPEDANCE

is_delta: false

traj_interpolator_cfg:
  traj_interpolator_type: LINEAR_JOINT_POSITION
  time_fraction: 0.3

joint_kp: [300.0, 300.0, 300.0, 300.0, 225.0, 450.0, 150.0]
joint_kd: [20.0, 20.0, 20.0, 20.0, 7.5, 15.0, 5.0] #[50.0, 50.0, 50.0, 50.0, 30.0, 25.0, 15.0] #[10., 10.,10., 10., 3.75, 7.5, 2.5] #[20., 20., 20., 20., 7.5, 15.0, 5.0]
max_delta_q: [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2] #[0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]

state_estimator_cfg:
  is_estimation: true
  state_estimator_type: EXPONENTIAL_SMOOTHING
  alpha_q: 0.9
  alpha_dq: 0.9
  alpha_eef: 1.0
  alpha_eef_vel: 1.0